import { Open_Sans } from 'next/font/google'
import styles from "./rootStyle.module.css"
import Link from "next/link"; 
import "./global.css"

const openSans = Open_Sans({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <header>
      <h1>
        <Link className={styles.homelink} href="/home">Tech Team</Link>
       </h1>
      <h2>
        <Link className={styles.menuBarLink} href="/blog">Blog</Link>
       </h2>
       <h2>
        <Link className={styles.menuBarLink} href="/settings">Settings</Link>
       </h2>
       <h2>
        <Link className={styles.menuBarLink} href="/conference">Conference</Link>
       </h2>
       </header>
        {children}</body>
    </html>
  )
}
